import { jsPDF } from "jspdf";

export interface PrescriptionPdfInput {
  clinicName: string;
  doctorName: string;
  doctorTitle: string | null;
  patientName: string;
  date: string;
  medicines: { name: string; dosage: string; frequency: string; duration: string; instructions: string }[];
  notes: string;
}

const MARGIN_X = 48;
const PAGE_RIGHT = 548;

export function buildPrescriptionPdf(input: PrescriptionPdfInput): Blob {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = 56;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(input.clinicName || "DentVerse Clinic", MARGIN_X, y);
  y += 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`${input.doctorName}${input.doctorTitle ? " · " + input.doctorTitle : ""}`, MARGIN_X, y);
  y += 24;

  doc.setDrawColor(200);
  doc.line(MARGIN_X, y, PAGE_RIGHT, y);
  y += 20;

  doc.setFontSize(10);
  doc.text(`Date: ${input.date}`, MARGIN_X, y);
  doc.text(`Patient: ${input.patientName}`, 320, y);
  y += 30;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(18);
  doc.text("Rx", MARGIN_X, y);
  y += 22;

  doc.setFontSize(11);
  const medicines = input.medicines.filter((m) => m.name.trim());
  if (medicines.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.text("No medicines listed.", MARGIN_X, y);
    y += 16;
  }
  medicines.forEach((m, i) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${i + 1}. ${m.name}`, MARGIN_X, y);
    y += 15;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`${m.dosage} · ${m.frequency} · ${m.duration}`, MARGIN_X + 12, y);
    y += 13;
    if (m.instructions) {
      doc.text(m.instructions, MARGIN_X + 12, y);
      y += 13;
    }
    doc.setFontSize(11);
    y += 8;
  });

  if (input.notes) {
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("Notes", MARGIN_X, y);
    y += 14;
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(input.notes, PAGE_RIGHT - MARGIN_X);
    doc.text(lines, MARGIN_X, y);
    y += lines.length * 13;
  }

  y += 30;
  doc.setDrawColor(200);
  doc.line(MARGIN_X, y, PAGE_RIGHT, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Generated by DentVerse.", MARGIN_X, y);

  return doc.output("blob");
}

export async function sha256Hex(blob: Blob): Promise<string> {
  const buffer = await blob.arrayBuffer();
  const digest = await crypto.subtle.digest("SHA-256", buffer);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}
