import * as React from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import {
  FileText,
  ArrowLeft,
  Sparkles,
  Plus,
  Trash2,
  Send,
  CheckCircle2,
  MessageCircle,
  Pencil,
  Eye,
  ShieldCheck,
  Printer,
  Loader2,
  Stethoscope,
  Mic,
  AudioWaveform,
  Brain,
} from "lucide-react";
import { useAppState } from "@/context/AppStateContext";
import { currentDoctor } from "@/data/mockData";
import type { Prescription as PrescriptionRecord } from "@/data/mockData";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

type MedRow = { name: string; dosage: string; frequency: string; duration: string; instructions: string };

const emptyRow: MedRow = { name: "", dosage: "", frequency: "", duration: "", instructions: "" };

const AI_SUGGESTIONS: MedRow[] = [
  { name: "Sensodyne Rapid Relief", dosage: "Apply pea-sized amount", frequency: "Twice daily", duration: "4 weeks", instructions: "Massage on affected teeth for 1 min, do not rinse immediately." },
  { name: "Ibuprofen 400mg", dosage: "1 tablet", frequency: "Every 8 hours as needed", duration: "3 days", instructions: "Take after food." },
];

const DICTATED_RX: MedRow[] = [
  { name: "Amoxicillin 500mg", dosage: "1 capsule", frequency: "Every 8 hours", duration: "5 days", instructions: "Complete full course, take after food." },
  { name: "Chlorhexidine Mouthwash 0.2%", dosage: "10ml rinse", frequency: "Twice daily", duration: "1 week", instructions: "Do not eat or drink for 30 minutes after use." },
];

type DictateStage = "idle" | "listening" | "processing";

function fakeSignatureHash(seed: string) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  return `SIG-${h.toString(16).toUpperCase().padStart(8, "0")}`;
}

function RxDocument({
  patientName,
  date,
  medicines,
  notes,
  signed,
}: {
  patientName: string;
  date: string;
  medicines: MedRow[];
  notes: string;
  signed: boolean;
}) {
  return (
    <div className="rounded-lg border border-border bg-white p-6 text-foreground">
      <div className="flex items-start justify-between border-b border-border pb-4">
        <div className="flex items-center gap-2">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
            <Stethoscope className="h-5 w-5" />
          </div>
          <div>
            <p className="font-bold">{currentDoctor.clinic}</p>
            <p className="text-xs text-muted-foreground">{currentDoctor.name} · {currentDoctor.title}</p>
          </div>
        </div>
        <div className="text-right text-xs text-muted-foreground">
          <p>Date: {date}</p>
          <p>Patient: {patientName}</p>
        </div>
      </div>

      <p className="mt-4 text-2xl font-serif italic text-primary">℞</p>
      <div className="mt-2 space-y-3">
        {medicines.filter((m) => m.name.trim()).map((m, i) => (
          <div key={i} className="border-b border-dashed border-border pb-2 text-sm">
            <p className="font-semibold">{i + 1}. {m.name}</p>
            <p className="text-muted-foreground">{m.dosage} · {m.frequency} · {m.duration}</p>
            {m.instructions && <p className="text-xs text-muted-foreground">{m.instructions}</p>}
          </div>
        ))}
        {medicines.filter((m) => m.name.trim()).length === 0 && (
          <p className="text-sm text-muted-foreground">No medicines added yet.</p>
        )}
      </div>

      {notes && (
        <div className="mt-4">
          <p className="text-xs font-medium text-muted-foreground">Notes</p>
          <p className="text-sm">{notes}</p>
        </div>
      )}

      <div className="mt-8 flex items-end justify-between border-t border-border pt-4">
        <p className="text-[11px] text-muted-foreground">Generated by DentVerse — for demonstration purposes only.</p>
        {signed ? (
          <div className="text-right">
            <p className="font-serif text-lg italic text-primary">{currentDoctor.name}</p>
            <div className="mt-1 flex items-center justify-end gap-1 text-[11px] font-medium text-success">
              <ShieldCheck className="h-3.5 w-3.5" /> Digitally Signed
            </div>
            <p className="text-[10px] text-muted-foreground">{fakeSignatureHash(patientName + date)} · {date}</p>
          </div>
        ) : (
          <p className="text-[11px] text-muted-foreground">Not yet signed</p>
        )}
      </div>
    </div>
  );
}

export default function Prescription() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { patients, addPrescription } = useAppState();
  const patient = patients.find((p) => p.id === id);

  const [mode, setMode] = React.useState<"edit" | "preview">("edit");
  const [rows, setRows] = React.useState<MedRow[]>([{ ...emptyRow }]);
  const [notes, setNotes] = React.useState("");
  const [signed, setSigned] = React.useState(false);
  const [generating, setGenerating] = React.useState(false);
  const [sent, setSent] = React.useState(false);
  const [historyPreview, setHistoryPreview] = React.useState<PrescriptionRecord | null>(null);
  const [dictateStage, setDictateStage] = React.useState<DictateStage>("idle");

  if (!patient) {
    return (
      <div className="py-20 text-center">
        <p className="text-muted-foreground">Patient not found.</p>
        <Button className="mt-4" onClick={() => navigate("/dashboard/patients")}>Back to Patients</Button>
      </div>
    );
  }

  const applyAiSuggestions = () => {
    setRows(AI_SUGGESTIONS.map((r) => ({ ...r })));
    setNotes(
      patient.chartNotes[0]
        ? `Based on latest chart note: ${patient.chartNotes[0].soap.assessment}`
        : "AI-suggested prescription based on patient history."
    );
  };

  const startDictation = () => {
    if (dictateStage !== "idle") return;
    setDictateStage("listening");
    setTimeout(() => {
      setDictateStage("processing");
      setTimeout(() => {
        setRows(DICTATED_RX.map((r) => ({ ...r })));
        setNotes("Filled from voice dictation via Sarvam AI — review before sending.");
        setDictateStage("idle");
      }, 1300);
    }, 1800);
  };

  const updateRow = (i: number, field: keyof MedRow, value: string) => {
    setRows((prev) => prev.map((r, idx) => (idx === i ? { ...r, [field]: value } : r)));
  };

  const addRow = () => setRows((prev) => [...prev, { ...emptyRow }]);
  const removeRow = (i: number) => setRows((prev) => prev.filter((_, idx) => idx !== i));

  const validMeds = rows.filter((r) => r.name.trim() !== "");

  const goToPreview = () => {
    if (validMeds.length === 0) return;
    setMode("preview");
  };

  const generateSignedPdf = () => {
    setGenerating(true);
    setTimeout(() => {
      setGenerating(false);
      setSigned(true);
    }, 900);
  };

  const handlePrint = () => window.print();

  const handleSend = () => {
    if (validMeds.length === 0) return;
    addPrescription(patient.id, {
      id: `rx${Date.now()}`,
      date: "2026-07-10",
      status: "Sent to Patient",
      notes,
      medicines: validMeds,
      signed,
    });
    setSent(true);
  };

  const resetForm = () => {
    setRows([{ ...emptyRow }]);
    setNotes("");
    setSigned(false);
    setMode("edit");
    setSent(false);
  };

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <Link to={`/patient/${patient.id}`} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground no-print">
        <ArrowLeft className="h-4 w-4" /> Back to {patient.name}
      </Link>

      <div className="no-print">
        <h1 className="flex items-center gap-2 text-2xl font-bold tracking-tight">
          <FileText className="h-6 w-6 text-primary" /> Prescription
        </h1>
        <p className="text-sm text-muted-foreground">Preview, digitally sign, and send a prescription to {patient.name} over WhatsApp.</p>
      </div>

      <Tabs defaultValue="new">
        <TabsList className="no-print">
          <TabsTrigger value="new">New Prescription</TabsTrigger>
          <TabsTrigger value="history">Previous Prescriptions ({patient.prescriptions.length})</TabsTrigger>
        </TabsList>

        <TabsContent value="new">
          {sent ? (
            <Card className="border-success/30 bg-success/5">
              <CardContent className="flex flex-col items-center gap-4 py-12 text-center">
                <div className="flex h-14 w-14 items-center justify-center rounded-full bg-success/10 text-success">
                  <CheckCircle2 className="h-7 w-7" />
                </div>
                <div>
                  <p className="text-lg font-semibold">Prescription sent</p>
                  <p className="text-sm text-muted-foreground">
                    Delivered to {patient.name} on WhatsApp ({patient.phone}){signed && " · Digitally Signed PDF attached"}
                  </p>
                </div>
                <div className="w-full max-w-sm rounded-lg bg-[#e5ded5] p-4 text-left">
                  <div className="rounded-lg bg-[#d9fdd3] px-3 py-2 text-sm shadow-sm">
                    <p className="mb-0.5 flex items-center gap-1 text-[10px] font-semibold text-primary">
                      <MessageCircle className="h-3 w-3" /> DentVerse Clinic
                    </p>
                    <p>Hi {patient.name.split(" ")[0]}, your prescription from Dr. Rao is ready. Tap to view dosage instructions. 💊</p>
                  </div>
                </div>
                <div className="flex flex-wrap justify-center gap-3">
                  <Button variant="outline" onClick={resetForm}>Create Another</Button>
                  <Button variant="outline" onClick={() => navigate(`/patient/${patient.id}`)}>Back to Workspace</Button>
                  <Button onClick={() => navigate(`/patient/${patient.id}/treatment-plan`)}>Build Treatment Plan</Button>
                </div>
              </CardContent>
            </Card>
          ) : mode === "edit" ? (
            <div className="space-y-4">
              <Card className="border-primary/30 bg-secondary/30">
                <CardContent className="flex flex-col items-center gap-3 py-8 text-center">
                  {dictateStage === "idle" && (
                    <>
                      <button
                        onClick={startDictation}
                        aria-label="Start voice dictation with Sarvam AI"
                        className="flex h-16 w-16 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-lg transition-transform hover:scale-105"
                      >
                        <Mic className="h-7 w-7" />
                      </button>
                      <div>
                        <p className="text-sm font-medium">Tap the mic and dictate the prescription</p>
                        <p className="text-xs text-muted-foreground">Sarvam AI transcribes it and fills the form for you — no typing needed.</p>
                      </div>
                    </>
                  )}
                  {dictateStage === "listening" && (
                    <>
                      <div className="relative flex h-16 w-16 items-center justify-center">
                        <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-destructive/30" />
                        <div className="relative flex h-16 w-16 items-center justify-center rounded-full bg-destructive text-destructive-foreground">
                          <Mic className="h-7 w-7" />
                        </div>
                      </div>
                      <p className="text-sm font-medium">Listening...</p>
                      <p className="text-xs text-muted-foreground">Describe the medicines, dosage, and instructions.</p>
                    </>
                  )}
                  {dictateStage === "processing" && (
                    <>
                      <div className="flex h-16 w-16 items-center justify-center rounded-full bg-secondary text-primary">
                        <Brain className="h-7 w-7 animate-pulse" />
                      </div>
                      <p className="flex items-center gap-1.5 text-sm font-medium">
                        <AudioWaveform className="h-4 w-4 animate-pulse" /> Sarvam AI is transcribing and filling the prescription...
                      </p>
                    </>
                  )}
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="flex-row items-center justify-between space-y-0">
                  <div>
                    <CardTitle>Medicines</CardTitle>
                    <CardDescription>Auto-filled from dictation, or add medications manually and let AI suggest based on the chart note.</CardDescription>
                  </div>
                  <Button variant="secondary" size="sm" onClick={applyAiSuggestions}>
                    <Sparkles className="h-4 w-4" /> AI Suggest
                  </Button>
                </CardHeader>
                <CardContent className="space-y-4">
                {rows.map((row, i) => (
                  <div key={i} className="rounded-lg border border-border p-4">
                    <div className="mb-3 flex items-center justify-between">
                      <Badge variant="outline">Medicine {i + 1}</Badge>
                      {rows.length > 1 && (
                        <button onClick={() => removeRow(i)} className="text-muted-foreground hover:text-destructive">
                          <Trash2 className="h-4 w-4" />
                        </button>
                      )}
                    </div>
                    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                      <div className="space-y-1.5 sm:col-span-2">
                        <Label>Name</Label>
                        <Input value={row.name} onChange={(e) => updateRow(i, "name", e.target.value)} placeholder="e.g. Amoxicillin 500mg" />
                      </div>
                      <div className="space-y-1.5">
                        <Label>Dosage</Label>
                        <Input value={row.dosage} onChange={(e) => updateRow(i, "dosage", e.target.value)} placeholder="1 capsule" />
                      </div>
                      <div className="space-y-1.5">
                        <Label>Frequency</Label>
                        <Input value={row.frequency} onChange={(e) => updateRow(i, "frequency", e.target.value)} placeholder="Every 8 hours" />
                      </div>
                      <div className="space-y-1.5">
                        <Label>Duration</Label>
                        <Input value={row.duration} onChange={(e) => updateRow(i, "duration", e.target.value)} placeholder="5 days" />
                      </div>
                      <div className="space-y-1.5">
                        <Label>Instructions</Label>
                        <Input value={row.instructions} onChange={(e) => updateRow(i, "instructions", e.target.value)} placeholder="Take after food" />
                      </div>
                    </div>
                  </div>
                ))}

                <Button variant="outline" size="sm" onClick={addRow}>
                  <Plus className="h-4 w-4" /> Add Medicine
                </Button>

                <div className="space-y-1.5 pt-2">
                  <Label>Notes for Patient</Label>
                  <Textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={3} placeholder="Any additional instructions..." />
                </div>

                <Button onClick={goToPreview} className="w-full" size="lg" disabled={validMeds.length === 0}>
                  <Eye className="h-4 w-4" /> Preview Prescription
                </Button>
                </CardContent>
              </Card>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="printable-area">
                <RxDocument patientName={patient.name} date="2026-07-10" medicines={rows} notes={notes} signed={signed} />
              </div>

              <Card className="no-print">
                <CardContent className="flex flex-wrap items-center justify-between gap-3 p-4">
                  <Button variant="outline" onClick={() => setMode("edit")}>
                    <Pencil className="h-4 w-4" /> Back to Edit
                  </Button>
                  <div className="flex flex-wrap gap-2">
                    {!signed ? (
                      <Button variant="secondary" onClick={generateSignedPdf} disabled={generating}>
                        {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShieldCheck className="h-4 w-4" />}
                        {generating ? "Generating..." : "Generate Digitally Signed PDF"}
                      </Button>
                    ) : (
                      <Button variant="secondary" onClick={handlePrint}>
                        <Printer className="h-4 w-4" /> Print / Save as PDF
                      </Button>
                    )}
                    <Button onClick={handleSend}>
                      <Send className="h-4 w-4" /> Send to Patient via WhatsApp
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          )}
        </TabsContent>

        <TabsContent value="history" className="space-y-3 no-print">
          {patient.prescriptions.map((rx) => (
            <Card key={rx.id}>
              <CardContent className="p-5">
                <div className="flex items-center justify-between">
                  <p className="text-sm font-semibold">{rx.date}</p>
                  <div className="flex items-center gap-2">
                    {rx.signed && (
                      <Badge variant="outline" className="gap-1 text-success">
                        <ShieldCheck className="h-3 w-3" /> Signed
                      </Badge>
                    )}
                    <Badge variant={rx.status === "Sent to Patient" ? "success" : "muted"}>{rx.status}</Badge>
                  </div>
                </div>
                <div className="mt-3 space-y-2">
                  {rx.medicines.map((m, idx) => (
                    <div key={idx} className="rounded-md bg-muted/50 p-3 text-sm">
                      <p className="font-medium">{m.name}</p>
                      <p className="text-xs text-muted-foreground">
                        {m.dosage} · {m.frequency} · {m.duration}
                      </p>
                      {m.instructions && <p className="mt-1 text-xs text-muted-foreground">{m.instructions}</p>}
                    </div>
                  ))}
                </div>
                {rx.notes && <p className="mt-3 text-xs italic text-muted-foreground">{rx.notes}</p>}
                <Button variant="outline" size="sm" className="mt-3" onClick={() => setHistoryPreview(rx)}>
                  <Eye className="h-3.5 w-3.5" /> Preview
                </Button>
              </CardContent>
            </Card>
          ))}
          {patient.prescriptions.length === 0 && (
            <p className="py-10 text-center text-sm text-muted-foreground">No prescriptions issued yet.</p>
          )}
        </TabsContent>
      </Tabs>

      <Dialog open={!!historyPreview} onOpenChange={(open) => !open && setHistoryPreview(null)}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Prescription Preview</DialogTitle>
          </DialogHeader>
          {historyPreview && (
            <RxDocument
              patientName={patient.name}
              date={historyPreview.date}
              medicines={historyPreview.medicines}
              notes={historyPreview.notes}
              signed={!!historyPreview.signed}
            />
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
